function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -10; // button_choice_a
	global.__objectDepths[1] = -10; // button_choice_b
	global.__objectDepths[2] = -10; // button_choice_c
	global.__objectDepths[3] = 0; // head_player
	global.__objectDepths[4] = 0; // head_player_menu
	global.__objectDepths[5] = 0; // head_sophia
	global.__objectDepths[6] = 0; // head_chris
	global.__objectDepths[7] = 0; // head_chandra
	global.__objectDepths[8] = 2; // head_jacob
	global.__objectDepths[9] = 0; // head_peter
	global.__objectDepths[10] = 0; // head_lily
	global.__objectDepths[11] = 0; // head_isaac
	global.__objectDepths[12] = 0; // head_cory
	global.__objectDepths[13] = 0; // head_adam
	global.__objectDepths[14] = 0; // head_pj
	global.__objectDepths[15] = 0; // title
	global.__objectDepths[16] = 0; // npc_bios
	global.__objectDepths[17] = 0; // thirteenletter_teaser
	global.__objectDepths[18] = 0; // button_character_next
	global.__objectDepths[19] = 0; // button_character_back
	global.__objectDepths[20] = 0; // button_back
	global.__objectDepths[21] = 0; // button_extras
	global.__objectDepths[22] = 0; // button_credits_twitter
	global.__objectDepths[23] = 0; // button_main_twitter
	global.__objectDepths[24] = 0; // button_credits_facebook
	global.__objectDepths[25] = 0; // button_main_facebook
	global.__objectDepths[26] = 0; // button_credits
	global.__objectDepths[27] = 0; // button_newgame
	global.__objectDepths[28] = 0; // button_continue
	global.__objectDepths[29] = 0; // button_quit
	global.__objectDepths[30] = 0; // button_bios
	global.__objectDepths[31] = 0; // menu_title_credits
	global.__objectDepths[32] = 0; // menu_title_staytuned
	global.__objectDepths[33] = 0; // menu_title
	global.__objectDepths[34] = 0; // genetix_logo
	global.__objectDepths[35] = 0; // button_menu_winterbreak
	global.__objectDepths[36] = 0; // button_menu_summerbreak
	global.__objectDepths[37] = 0; // button_menu_springbreak
	global.__objectDepths[38] = 0; // button_winterbreak
	global.__objectDepths[39] = 0; // button_summerbreak
	global.__objectDepths[40] = 0; // button_springbreak
	global.__objectDepths[41] = 0; // button_catapult
	global.__objectDepths[42] = 0; // button_fartomatic
	global.__objectDepths[43] = 0; // button_sound
	global.__objectDepths[44] = -100; // store
	global.__objectDepths[45] = 0; // default_choice
	global.__objectDepths[46] = -10; // notification
	global.__objectDepths[47] = -10; // player_look_choose
	global.__objectDepths[48] = -10; // button_confirm_look
	global.__objectDepths[49] = 0; // chapter_01
	global.__objectDepths[50] = 0; // chapter_02
	global.__objectDepths[51] = 0; // chapter_03
	global.__objectDepths[52] = 0; // chapter_04
	global.__objectDepths[53] = 0; // chapter_05
	global.__objectDepths[54] = 0; // chapter_06
	global.__objectDepths[55] = 0; // chapter_07
	global.__objectDepths[56] = 0; // chapter_08
	global.__objectDepths[57] = 0; // chapter_09
	global.__objectDepths[58] = 0; // chapter_10
	global.__objectDepths[59] = 0; // chapter_11
	global.__objectDepths[60] = 0; // chapter_12
	global.__objectDepths[61] = 0; // chapter_13
	global.__objectDepths[62] = 0; // chapter_14
	global.__objectDepths[63] = 0; // chapter_15
	global.__objectDepths[64] = 0; // chapter_16
	global.__objectDepths[65] = 0; // chapter_17
	global.__objectDepths[66] = 0; // chapter_18
	global.__objectDepths[67] = 0; // chapter_19
	global.__objectDepths[68] = 0; // chapter_20
	global.__objectDepths[69] = 0; // chapter_21
	global.__objectDepths[70] = 0; // chapter_22
	global.__objectDepths[71] = 0; // chapter_23
	global.__objectDepths[72] = 0; // chapter_24
	global.__objectDepths[73] = 0; // chapter_25
	global.__objectDepths[74] = 0; // chapter_26
	global.__objectDepths[75] = 0; // chapter_27
	global.__objectDepths[76] = 0; // chapter_28
	global.__objectDepths[77] = 0; // chapter_29
	global.__objectDepths[78] = 0; // chapter_30
	global.__objectDepths[79] = 0; // chapter_31
	global.__objectDepths[80] = 0; // chapter_32
	global.__objectDepths[81] = 0; // chapter_33
	global.__objectDepths[82] = 0; // chapter_34
	global.__objectDepths[83] = 0; // chapter_souldefender
	global.__objectDepths[84] = 0; // chapter_35
	global.__objectDepths[85] = 0; // chapter_36
	global.__objectDepths[86] = 0; // chapter_37
	global.__objectDepths[87] = 0; // chapter_38
	global.__objectDepths[88] = 0; // chapter_39
	global.__objectDepths[89] = 0; // chapter_40
	global.__objectDepths[90] = 0; // chapter_41
	global.__objectDepths[91] = 0; // chapter_42
	global.__objectDepths[92] = 0; // chapter_43
	global.__objectDepths[93] = 0; // chapter_44
	global.__objectDepths[94] = 0; // extras_title
	global.__objectDepths[95] = 0; // icon_catapult
	global.__objectDepths[96] = 0; // icon_13letters
	global.__objectDepths[97] = 0; // icon_monstertrap
	global.__objectDepths[98] = 0; // icon_scarystories
	global.__objectDepths[99] = 0; // icon_mysterywords
	global.__objectDepths[100] = 0; // icon_souldefender


	global.__objectNames[0] = "button_choice_a";
	global.__objectNames[1] = "button_choice_b";
	global.__objectNames[2] = "button_choice_c";
	global.__objectNames[3] = "head_player";
	global.__objectNames[4] = "head_player_menu";
	global.__objectNames[5] = "head_sophia";
	global.__objectNames[6] = "head_chris";
	global.__objectNames[7] = "head_chandra";
	global.__objectNames[8] = "head_jacob";
	global.__objectNames[9] = "head_peter";
	global.__objectNames[10] = "head_lily";
	global.__objectNames[11] = "head_isaac";
	global.__objectNames[12] = "head_cory";
	global.__objectNames[13] = "head_adam";
	global.__objectNames[14] = "head_pj";
	global.__objectNames[15] = "title";
	global.__objectNames[16] = "npc_bios";
	global.__objectNames[17] = "thirteenletter_teaser";
	global.__objectNames[18] = "button_character_next";
	global.__objectNames[19] = "button_character_back";
	global.__objectNames[20] = "button_back";
	global.__objectNames[21] = "button_extras";
	global.__objectNames[22] = "button_credits_twitter";
	global.__objectNames[23] = "button_main_twitter";
	global.__objectNames[24] = "button_credits_facebook";
	global.__objectNames[25] = "button_main_facebook";
	global.__objectNames[26] = "button_credits";
	global.__objectNames[27] = "button_newgame";
	global.__objectNames[28] = "button_continue";
	global.__objectNames[29] = "button_quit";
	global.__objectNames[30] = "button_bios";
	global.__objectNames[31] = "menu_title_credits";
	global.__objectNames[32] = "menu_title_staytuned";
	global.__objectNames[33] = "menu_title";
	global.__objectNames[34] = "genetix_logo";
	global.__objectNames[35] = "button_menu_winterbreak";
	global.__objectNames[36] = "button_menu_summerbreak";
	global.__objectNames[37] = "button_menu_springbreak";
	global.__objectNames[38] = "button_winterbreak";
	global.__objectNames[39] = "button_summerbreak";
	global.__objectNames[40] = "button_springbreak";
	global.__objectNames[41] = "button_catapult";
	global.__objectNames[42] = "button_fartomatic";
	global.__objectNames[43] = "button_sound";
	global.__objectNames[44] = "store";
	global.__objectNames[45] = "default_choice";
	global.__objectNames[46] = "notification";
	global.__objectNames[47] = "player_look_choose";
	global.__objectNames[48] = "button_confirm_look";
	global.__objectNames[49] = "chapter_01";
	global.__objectNames[50] = "chapter_02";
	global.__objectNames[51] = "chapter_03";
	global.__objectNames[52] = "chapter_04";
	global.__objectNames[53] = "chapter_05";
	global.__objectNames[54] = "chapter_06";
	global.__objectNames[55] = "chapter_07";
	global.__objectNames[56] = "chapter_08";
	global.__objectNames[57] = "chapter_09";
	global.__objectNames[58] = "chapter_10";
	global.__objectNames[59] = "chapter_11";
	global.__objectNames[60] = "chapter_12";
	global.__objectNames[61] = "chapter_13";
	global.__objectNames[62] = "chapter_14";
	global.__objectNames[63] = "chapter_15";
	global.__objectNames[64] = "chapter_16";
	global.__objectNames[65] = "chapter_17";
	global.__objectNames[66] = "chapter_18";
	global.__objectNames[67] = "chapter_19";
	global.__objectNames[68] = "chapter_20";
	global.__objectNames[69] = "chapter_21";
	global.__objectNames[70] = "chapter_22";
	global.__objectNames[71] = "chapter_23";
	global.__objectNames[72] = "chapter_24";
	global.__objectNames[73] = "chapter_25";
	global.__objectNames[74] = "chapter_26";
	global.__objectNames[75] = "chapter_27";
	global.__objectNames[76] = "chapter_28";
	global.__objectNames[77] = "chapter_29";
	global.__objectNames[78] = "chapter_30";
	global.__objectNames[79] = "chapter_31";
	global.__objectNames[80] = "chapter_32";
	global.__objectNames[81] = "chapter_33";
	global.__objectNames[82] = "chapter_34";
	global.__objectNames[83] = "chapter_souldefender";
	global.__objectNames[84] = "chapter_35";
	global.__objectNames[85] = "chapter_36";
	global.__objectNames[86] = "chapter_37";
	global.__objectNames[87] = "chapter_38";
	global.__objectNames[88] = "chapter_39";
	global.__objectNames[89] = "chapter_40";
	global.__objectNames[90] = "chapter_41";
	global.__objectNames[91] = "chapter_42";
	global.__objectNames[92] = "chapter_43";
	global.__objectNames[93] = "chapter_44";
	global.__objectNames[94] = "extras_title";
	global.__objectNames[95] = "icon_catapult";
	global.__objectNames[96] = "icon_13letters";
	global.__objectNames[97] = "icon_monstertrap";
	global.__objectNames[98] = "icon_scarystories";
	global.__objectNames[99] = "icon_mysterywords";
	global.__objectNames[100] = "icon_souldefender";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
